### PR TITLE
Add Microsoft Code of Conduct

### PR DESCRIPTION
**Pull request by andschwa**
We should have this on every repo that is Microsoft code.

### CODE REVIEW

**Comment by andschwa** [comment]
Also ran M-x whitespace-cleanup.

**Comment by paulcallen** [comment]
I am confused what I am seeing here

**Comment by paulcallen** [comment]
I am guessing a quick rebase will make this look more understandable. With that in mind I cherry-picked your commit.

**Comment by andschwa** [comment]
Thanks!

**Pull request closed without merging**
